### ISSUE TITLE
permission denied when trying to git cloud-drive-extension

### ISSUE THREAD

**Issue by fitbodylife** [exo-addons/cloud-drive-extension#30]
this is the error i get

OS name: "linux", version: "3.16-0.bpo.2-amd64", arch: "amd64", family: "unix"
bitnami@bitnami-exoplatform-eee5:/opt/bitnami/apache-tomcat$ cd ..
bitnami@bitnami-exoplatform-eee5:/opt/bitnami$ git clone git@github.com:exo-addons/cloud-drive-extension.git
fatal: could not create work tree dir 'cloud-drive-extension'.: Permission denied
bitnami@bitnami-exoplatform-eee5:/opt/bitnami$ sudo git clone git@github.com:exo-addons/cloud-drive-extension.git
Cloning into 'cloud-drive-extension'...
Permission denied (publickey).

**Comment by pnedonosko** [comment]
Closed as outdated.
