### ISSUE TITLE
Can't edit google docs in firefox, but can in chromium

### ISSUE THREAD

**Issue by 3ruce** [exo-addons/cloud-drive-extension#32]
The addon seems to be working fine after some initial testing but I can't edit google docs in firefox, but can in chromium. Both browsers are up to date on xubuntu 12.04...

It's nothing major but I thought I'd add a comment...

**Comment by pnedonosko** [comment]
Thank you for tracking this issue. It should be fixed in next stable version. Indeed I must admit that for Google Drive behaviour changed by them. All non-Google file types have CORS restriction and cannot be shown embedded in a frame now. Later we'll see how this restriction can be bypassed, but in next version it will be as described above.

**Comment by 3ruce** [comment]
Thank you for the update - do you know when the next release will be?

**Comment by pnedonosko** [comment]
Hi, Cloud Drive 1.2.0 (for Platform 4.1) and 1.1.0 (Platform 4.0) released and available in eXo catalog.
Reopen this issue if it is still actual. Take in account #35 also.

**Comment by 3ruce** [comment]
Still no joy after updating the add-on - I've disabled some add-ons in FF too... any ideas/anything else I can test?

**Comment by pnedonosko** [comment]
Weird stuff, but I need reproduce it. Please describe a bit more in details: FF version, OS, your steps from connecting the drive to use (open/view/edit) the file, actual for all files or for some of them only (office formats, images, Google doc/spreadhseet/presentation). If possible try check in FF dev tools for messages in console (logs), screenshots may help also.
Thank you.

**Comment by 3ruce** [comment]
Thanks Pnedonosko - I'll get on to this but it might take me a few days or more...

**Comment by pnedonosko** [comment]
Resolved in 1.1.1 and 1.2.1 versions.

**Comment by 3ruce** [comment]
Thanks Peter, I'll check this out...

**Comment by 3ruce** [comment]
Hi Peter, do you know when the latest release will be in the exo repositories?

**Comment by pnedonosko** [comment]
It is already in the Maven and will take several hours to get to Addons catalog I guess.

**Comment by 3ruce** [comment]
ok  - cool, I tried it earlier and it was still 1.2.0-RC2

**Comment by pnedonosko** [comment]
Please check version 1.2.1 from Add-ons catalog.

**Comment by 3ruce** [comment]
Working fine thanks Peter...
