### ISSUE TITLE
GoogleDrive continuous synchronizing and cancels Edit mode

### ISSUE THREAD

**Issue by pnedonosko** [exo-addons/cloud-drive-extension#35]
When opening a document from Google Drive for editing, a file page refreshes in seconds and thus loads back to default view mode. This is something introduced in previous versions as initially Edit feature have been working well - check new auto-refresh logic and avoid refreshing when file is open (or even when anything else than folder listing open).
Issued by eXo Community member. Confirmed in 1.1.0 and 1.2.0.

**Comment by pnedonosko** [comment]
A workaround from the community member: open two or more Google Drive files from Cloud Drive to stop synchronizing with the previously open documents.

**Comment by pnedonosko** [comment]
Proposed commit tested on PLF4.0 and 4.1 in Chrome, FF and Safari (all on Mac OSX).

**Comment by marwenmema** [comment]
@pnedonosko I have experienced the same bug and was about to report it (PLF4.1.1). Glad to see it already reported. I want to start showing this great add-on in some of my demos but these auto-refreshes are ruining the fun. It would be awesome if they fixed.

**Comment by pnedonosko** [comment]
@marwenmema can you use the latest snapshot version where it is fixed already

**Comment by marwenmema** [comment]
Great! Many thanks Peter.

**Comment by pnedonosko** [comment]
Resolved in 1.1.1 and 1.2.1 versions
