### ISSUE TITLE
Google docs is displayed only on half of the screen with PLF 4.2-RC1

### ISSUE THREAD

**Issue by thomasdelhomenie** [exo-addons/cloud-drive-extension#36]
Cloud Drive extension works fine on PLF 4.2-RC1 (at least for Google Drive) but the Google docs are displayed only on half of the screen :
![clouddrive](https://cloud.githubusercontent.com/assets/342645/8312294/08883a62-19dc-11e5-94e4-8f8b034a3f0e.png)

Same thing on Firefox and Chrome - with PLF 4.2-RC1 Tomcat and Cloud Drive 1.2.1

**Comment by pnedonosko** [comment]
Fix committed in master for 1.3.0 version.
