### ISSUE TITLE
[Gdrive] Do not see summary notification after syncronizing

### ISSUE THREAD

**Issue by thuha** [exo-addons/cloud-drive-extension#44]
Environment: PLF 4.2, cloud-drive-extension 1.3.0-RC1

Test steps:
– Step 1: Go to Personal Documents drive
– Step 2: Choose "Connect Cloud Documents" action
– Step 3: Choose "Connect your Google Drive" --> Allow Cloud Workspaces app in Google’s “Request for Permission” window --> Connect to Google Drive successfull => Google Drive folder is displayed in Personal Documents drive
– Step 4: Go to Google Drive application: create some files
– Step 5: Come back to PLF
– Step 6: Go to Site Explorer --> Choose Personal Documents drive --> Choose Icons View --> On Left panel: Right click on Google Drive folder at step 4 and choose "Sync with Google Drive" in context menu

=> Actual result: Some created file at step 4 is displayed in Google Drive folder without summary notification

=> Expected result: A notification with a summary of the updates will be shown (see ExpectedNotification.png) (base on http://blog.exoplatform.com/en/2013/02/28/exo-add-on-in-action-connecting-your-google-drive-to-exo-platform)

(Feedback from https://jira.exoplatform.org/browse/CLDINT-2052)

**Comment by pnedonosko** [comment]
Summary notifications removed since auto-sync introduced. But you still can find technical log in browser console.
