### ISSUE TITLE
Review pull request for upgrade plf43

### ISSUE THREAD

**Issue by quynhntn** [exo-addons/cloud-drive-extension#49]
https://github.com/exo-addons/cloud-drive-extension/pull/48

**Comment by pnedonosko** [comment]
What actual changes about PLF 4.3 in the pull-request? Do we have UI difference with 4.2 or changes in container components?
FYI version is wrong it will be 1.4.x for Platform 4.3. Use of infinispan configurations are only for tests - thus has no impact on the add-on functionality.

**Comment by quynhntn** [comment]
Hi Peter,

For the version, it's just the snapshot version for my branch, you can
change the version when merging into develop or other branches, I don't
have permission on that.

For the impact, yes, it does not impact on the add-on functionality. When
upgrade to new version of plf, there are some UT ran fail due to the
Cachable... class does not exist anymore. I changed some configuration to
make those passed.

Thanks,

Quynhnn.

**Comment by pnedonosko** [comment]
Ok for tests and versions, I'll apply this proposal. But tell me if it is critical for eXo Cloud if nothing impacted functionally. Otherwise you can use latest stable version 1.3.0 there.

**Comment by quynhntn** [comment]
Hi Peter,

This morning, I tried with 1.3.0 and 1.3.0-RC1. It builds success but it
throws exception when I launch UXP with cloud. It said:

Caused by: java.lang.NoSuchMethodError:
org.exoplatform.container.xml.ValuesParam.getValues()Ljava/util/ArrayList;
	at org.exoplatform.clouddrive.ecms.CloudDriveUIExtension.<init>(CloudDriveUIExtension.java:53)
~[exo-clouddrive-services-ecms-1.3.0.jar:1.3.0]

And yes, the UXP upgrade to plf43 and kernel-cloud 2.5.x-UXP-SNAPSHOT.
The above method does not exist anymore. It is "List<String>
getValues()"

Of course, it works fine with my branch, UXP can launch success with exo-cloud.

Please take a look at.

Thanks,

Quynhnn.

**Comment by pnedonosko** [comment]
Well I see the problem with the method - indeed it doesn't fixed in the pull request. Also I don't understand how it works on your branch, have you added that method back there?

**Comment by quynhntn** [comment]
Hi Peter,

For the problem, the return result is List<String> instead of ArrayList but
the treatment is the same as it is so it does not need any fixes, it just
needs to upgrade version of platform and JCR to make sure it does not have
any conflict.

Thanks,

Qunhnn.

**Comment by pnedonosko** [comment]
OK. Thank you for the study. I'll do an upgrade to PLF 4.3 and plan the release 1.4.
