### ISSUE TITLE
[CSS] The display of file name is not good

### ISSUE THREAD

**Issue by thuha** [exo-addons/cloud-drive-extension#54]
Ref issue https://jira.exoplatform.org/browse/CLDINT-2057
![cldint-2057](https://cloud.githubusercontent.com/assets/1137586/10782557/dec73f8c-7d83-11e5-8695-8534a074f4d6.png)

**Comment by pnedonosko** [comment]
No, it is not cloud drive issue. It is Platform, how it renders a files with extensions (in ECMS's `UIDocumentNodeList`): it sees a dot and assume it as a filename/extension separator. I don't think we should fix something on the addon level.

**Comment by pnedonosko** [comment]
If we will apply something to workaround the Platform behaviour, then it will also make bold all extensions (e.g. imgo.jpeg a whole name will be bold).

**Comment by pnedonosko** [comment]
Should be fixed on Platform side.
