### ISSUE TITLE
Proxy error : the proxy server could not handle the request from /portal/rest/clouddrive/drive/synchronize error reading from remote server

### ISSUE THREAD

**Issue by madhifallah** [exo-addons/cloud-drive-extension#62]
Proxy error : the proxy server could not handle the request from /portal/rest/clouddrive/drive/synchronize error reading from remote server

![google drive](https://cloud.githubusercontent.com/assets/2385389/23175907/3a0e49b8-f861-11e6-9364-ef840ff739fd.png)

I encounter this error from while to while.

I encreased my reverse proxy timeout and checking.

**Comment by pnedonosko** [comment]
If increasing the reverse proxy timeout fixed the problem, you might share the timeout value and close the issue. Thank you.

**Comment by madhifallah** [comment]
Yes I confirm it fixed the issue.
here are my values for clouddrive in the httpd reverse proxy configuration: 

ProxyPass    /portal/rest/clouddrive/connect http://localhost:8080/portal/rest/clouddrive/connect acquire=5000 retry=60 timeout=600 Keepalive=On
   ProxyPass    portal/rest/clouddrive/drive/synchronize http://localhost:8080/portal/rest/clouddrive/drive/synchronize acquire=5000 retry=60 timeout=600 Keepalive=On
